### ISSUE TITLE
Workspace settings ckeditor toolbar explodes

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#4721] opened 2019-10-03 07:23 UTC
cKeditor looks fine, but when you focus, the toolbar explodes out of bounds

**Comment by jjlankinen** [comment] 2019-10-25 08:15
Cannot reproduce this when testing with Chrome 78.0.3904.70 (Official Build) (64-bit) and Firefox 69.0.3 (64-bit).

Closing this for now and lets reopen if necessary in the future.

**Closed by jjlankinen** 2019-10-25 08:15 UTC
Labels: PLANNED, WORKSPACES, bug
