### ISSUE TITLE
Evalution tool takes long to load

### ISSUE THREAD

**Issue by issakainen** [otavanopisto/muikku#258] opened 2015-06-04 05:07 UTC
Also going to the second page hangs on the first time. After you reload the tool the second page comes up instantly.

Relevant stack trace

    2015-06-15 11:18:07,609 ERROR [org.jboss.as.ejb3.invocation] (default task-15) JBAS014134: EJB Invocation failed on component EvaluationPageBackingBean for method public void fi.muikku.plugins.evaluation.EvaluationPageBackingBean.setMaxStudents(java.lang.Integer): javax.ejb.EJBTransactionRolledbackException: JBAS
    014360: EJB 3.1 FR 4.3.14.1 concurrent access timeout on org.jboss.invocation.InterceptorContext@3f24fd38 - could not obtain lock within 5000 MILLISECONDS

**Comment by pkukkon** [comment] 2015-06-23 07:27
The overall performance of the Evaluation tool is admittedly somewhat poor. When the tool launched, it tried to load the first two pages of students concurrently. This ended up taking too long and caused an access timeout.

Possibly fixed by loading the first two pages subsequently. Couldn't actually reproduce the issue in development so won't close this issue until we can see if the fix makes any difference in production.

Overall performance of the tool still needs to be evaluated and improved but at least the second page of students should no longer hang.

**Comment by pkukkon** [comment] 2015-06-24 05:47
Looks like the fix works fine in production.

**Closed by pkukkon** 2015-06-24 05:47 UTC
Labels: bug
