### ISSUE TITLE
Check that archived students work correctly

### ISSUE THREAD

**Issue by ilmoeuro** [otavanopisto/muikku#3344] opened 2017-07-03 06:06 UTC
#### Source

http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1839

**Comment by pkukkon** [comment] 2018-01-26 05:28
Caused by synchronization issues between Muikku and Pyramus. Fixed in #3348 after which there have apparently been no tickets about similar behavior.

**Closed by pkukkon** 2018-01-26 05:28 UTC
Labels: bug, review
