### ISSUE TITLE
SingleResult returned 2 elements

### ISSUE THREAD

**Issue by petja-laitila** [otavanopisto/muikku#923] opened 2015-11-13 10:48 UTC
/rest/coursepicker/workspaces/: org.jboss.resteasy.spi.UnhandledException: javax.ejb.EJBException: javax.persistence.NonUniqueResultException: SingleResult query returned 2 elements

In this case this error breaks Coursepicker in production environment.

**Comment by ilmoeuro** [comment] 2015-11-13 11:11
Duplicate of #924

**Closed by ilmoeuro** 2015-11-13 11:11 UTC
Labels: bug, priority
