### ISSUE TITLE
Safari - saving issue when editing workspace materials

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#1270] opened 2016-01-20 06:45 UTC
> Minulla on ollut ongelmia muokata kursseja. Pulma, on se, että kohdassa jossa pitäisi lukea saved, lukee loaded tai unsaved kun menen muokkamaan kurssia. (välillä selaimen vaihto on auttanut, mutta aika usein muokkaaminen ei onnistu). Ei oikein meinaa tulla muokkaamisesta mitään. Mikä avuksi?

Teacher means workspace materials. Also says it works fine with chrome, but not with safari and internet explorer.

OsTicket ticket no. 343640
Stakeholder: Pekka Niemi

**Comment by issakainen** [comment] 2016-02-11 11:47
Was unable to reproduce the error with Safari (9.0.3 with OSX El Capitan). This smells like an issue that can be fixed by removing the https and using http? There were some similar errors back in the day...

**Comment by anttileppa** [comment] 2016-02-11 11:52
Should be fixed now and your guess was quite correct the issue was in Safari secure websocket handling (wss).

**Closed** 2016-02-15 10:31 UTC
Labels: bug
