### ISSUE TITLE
Connection lost when submitting assignment / autosaving task field

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2327] opened 2016-08-18 07:23 UTC
Muikku constantly loses connection when submitting assignment / autosaving taskfield. 

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=975

#### SH
Every student

**Comment by pkukkon** [comment] 2016-08-19 05:26
Possibly duplicate of #2255

**Closed** 2016-09-16 05:39 UTC
Labels: bug, helpdesk, priority
