### ISSUE TITLE
ToR - "Not found"-when clicking a workspace

### ISSUE THREAD

**Issue by avukkonen** [otavanopisto/muikku#2473] opened 2016-09-29 08:08 UTC
Muikku 2-course ? 

![screen shot 2016-09-29 at 11 00 14](https://cloud.githubusercontent.com/assets/3994573/18945848/06bb7fe8-8635-11e6-8b4b-0d92407f4117.png)

**Comment by pkukkon** [comment] 2016-10-03 09:36
Duplicate of #2472, fixed in #2147

**Closed** 2016-10-03 09:37 UTC
Labels: enhancement, in progress
