### ISSUE TITLE
Attached file in evaluation loads very slowly

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2299] opened 2016-08-10 12:05 UTC
When trying to open students attachments in file fields it takes very long time after browser actually starts downloading it. Browser connects for 20s+ before actually downloading the file for viewing,

#### Details

 - Performance problems with other file field download/upload operations too

#### OSticket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=982

#### SH
Kai Kaskela

**Comment by pkukkon** [comment] 2016-09-12 08:41
Most likely a duplicate of #2393.

**Closed** 2016-09-14 08:37 UTC
Labels: bug, helpdesk
