### ISSUE TITLE
Assignment's evaluation form occasionally does not load literal and grade

### ISSUE THREAD

**Issue by jjlankinen** [otavanopisto/muikku#2806] opened 2017-01-04 06:01 UTC
Sometimes ion new evaluation's assignment evaluation view form won't load assignment's literal and grade data when switching between assignment's evaluation views.

Possible culprit might be draft support or feature where assignment's evaluation data gets "saved" in the background.

#### OSTicket
http://helpdesk.muikkuverkko.fi/scp/tickets.php?id=1400

#### SH
Heli Viitanen

**Comment by pkukkon** [comment] 2017-01-09 12:03
Possible duplicate of #2731

**Comment by pkukkon** [comment] 2017-01-12 10:38
Confirmed duplicate of #2731

**Closed** 2017-01-12 10:38 UTC
Labels: bug, evaluation, helpdesk
